title: "Talko Denis"
email: talko.denis.andreevich@gmail.com
description: >-
  It's just my personal site.
baseurl: "" 
url: "https://talkodenis.github.io"
github_username: TalkoDenis

theme: minima
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-seo-tag
